// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internals.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "internals.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace artm {
namespace core {

namespace {

const ::google::protobuf::Descriptor* FloatArray_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  FloatArray_reflection_ = NULL;
const ::google::protobuf::Descriptor* Mask_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Mask_reflection_ = NULL;
const ::google::protobuf::Descriptor* ProcessorInput_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ProcessorInput_reflection_ = NULL;
const ::google::protobuf::Descriptor* ProcessorOutput_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ProcessorOutput_reflection_ = NULL;
const ::google::protobuf::Descriptor* ModelIncrement_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ModelIncrement_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_internals_2eproto() {
  protobuf_AddDesc_internals_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "internals.proto");
  GOOGLE_CHECK(file != NULL);
  FloatArray_descriptor_ = file->message_type(0);
  static const int FloatArray_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FloatArray, value_),
  };
  FloatArray_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      FloatArray_descriptor_,
      FloatArray::default_instance_,
      FloatArray_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FloatArray, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FloatArray, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(FloatArray));
  Mask_descriptor_ = file->message_type(1);
  static const int Mask_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Mask, value_),
  };
  Mask_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Mask_descriptor_,
      Mask::default_instance_,
      Mask_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Mask, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Mask, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Mask));
  ProcessorInput_descriptor_ = file->message_type(2);
  static const int ProcessorInput_offsets_[6] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProcessorInput, batch_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProcessorInput, batch_uuid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProcessorInput, data_loader_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProcessorInput, stream_mask_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProcessorInput, stream_name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProcessorInput, previous_processor_output_),
  };
  ProcessorInput_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ProcessorInput_descriptor_,
      ProcessorInput::default_instance_,
      ProcessorInput_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProcessorInput, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProcessorInput, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ProcessorInput));
  ProcessorOutput_descriptor_ = file->message_type(3);
  static const int ProcessorOutput_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProcessorOutput, batch_uuid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProcessorOutput, data_loader_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProcessorOutput, model_increment_),
  };
  ProcessorOutput_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ProcessorOutput_descriptor_,
      ProcessorOutput::default_instance_,
      ProcessorOutput_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProcessorOutput, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProcessorOutput, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ProcessorOutput));
  ModelIncrement_descriptor_ = file->message_type(4);
  static const int ModelIncrement_offsets_[10] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ModelIncrement, model_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ModelIncrement, topics_count_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ModelIncrement, items_processed_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ModelIncrement, discovered_token_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ModelIncrement, token_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ModelIncrement, token_increment_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ModelIncrement, score_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ModelIncrement, score_norm_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ModelIncrement, item_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ModelIncrement, theta_),
  };
  ModelIncrement_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ModelIncrement_descriptor_,
      ModelIncrement::default_instance_,
      ModelIncrement_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ModelIncrement, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ModelIncrement, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ModelIncrement));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_internals_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    FloatArray_descriptor_, &FloatArray::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Mask_descriptor_, &Mask::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ProcessorInput_descriptor_, &ProcessorInput::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ProcessorOutput_descriptor_, &ProcessorOutput::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ModelIncrement_descriptor_, &ModelIncrement::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_internals_2eproto() {
  delete FloatArray::default_instance_;
  delete FloatArray_reflection_;
  delete Mask::default_instance_;
  delete Mask_reflection_;
  delete ProcessorInput::default_instance_;
  delete ProcessorInput_reflection_;
  delete ProcessorOutput::default_instance_;
  delete ProcessorOutput_reflection_;
  delete ModelIncrement::default_instance_;
  delete ModelIncrement_reflection_;
}

void protobuf_AddDesc_internals_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::artm::protobuf_AddDesc_messages_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\017internals.proto\022\tartm.core\032\016messages.p"
    "roto\"\037\n\nFloatArray\022\021\n\005value\030\001 \003(\002B\002\020\001\"\031\n"
    "\004Mask\022\021\n\005value\030\001 \003(\010B\002\020\001\"\322\001\n\016ProcessorIn"
    "put\022\032\n\005batch\030\001 \002(\0132\013.artm.Batch\022\022\n\nbatch"
    "_uuid\030\002 \002(\t\022\026\n\016data_loader_id\030\003 \002(\005\022$\n\013s"
    "tream_mask\030\004 \003(\0132\017.artm.core.Mask\022\023\n\013str"
    "eam_name\030\005 \003(\t\022=\n\031previous_processor_out"
    "put\030\006 \001(\0132\032.artm.core.ProcessorOutput\"q\n"
    "\017ProcessorOutput\022\022\n\nbatch_uuid\030\001 \002(\t\022\026\n\016"
    "data_loader_id\030\002 \002(\005\0222\n\017model_increment\030"
    "\003 \003(\0132\031.artm.core.ModelIncrement\"\204\002\n\016Mod"
    "elIncrement\022\020\n\010model_id\030\001 \002(\005\022\024\n\014topics_"
    "count\030\002 \002(\005\022\027\n\017items_processed\030\003 \001(\005\022\030\n\020"
    "discovered_token\030\004 \003(\t\022\r\n\005token\030\005 \003(\t\022.\n"
    "\017token_increment\030\006 \003(\0132\025.artm.core.Float"
    "Array\022\r\n\005score\030\007 \003(\001\022\022\n\nscore_norm\030\010 \003(\001"
    "\022\017\n\007item_id\030\t \003(\005\022$\n\005theta\030\n \003(\0132\025.artm."
    "core.FloatArray", 695);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "internals.proto", &protobuf_RegisterTypes);
  FloatArray::default_instance_ = new FloatArray();
  Mask::default_instance_ = new Mask();
  ProcessorInput::default_instance_ = new ProcessorInput();
  ProcessorOutput::default_instance_ = new ProcessorOutput();
  ModelIncrement::default_instance_ = new ModelIncrement();
  FloatArray::default_instance_->InitAsDefaultInstance();
  Mask::default_instance_->InitAsDefaultInstance();
  ProcessorInput::default_instance_->InitAsDefaultInstance();
  ProcessorOutput::default_instance_->InitAsDefaultInstance();
  ModelIncrement::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_internals_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_internals_2eproto {
  StaticDescriptorInitializer_internals_2eproto() {
    protobuf_AddDesc_internals_2eproto();
  }
} static_descriptor_initializer_internals_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int FloatArray::kValueFieldNumber;
#endif  // !_MSC_VER

FloatArray::FloatArray()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void FloatArray::InitAsDefaultInstance() {
}

FloatArray::FloatArray(const FloatArray& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void FloatArray::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

FloatArray::~FloatArray() {
  SharedDtor();
}

void FloatArray::SharedDtor() {
  if (this != default_instance_) {
  }
}

void FloatArray::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* FloatArray::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return FloatArray_descriptor_;
}

const FloatArray& FloatArray::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_internals_2eproto();
  return *default_instance_;
}

FloatArray* FloatArray::default_instance_ = NULL;

FloatArray* FloatArray::New() const {
  return new FloatArray;
}

void FloatArray::Clear() {
  value_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool FloatArray::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated float value = 1 [packed = true];
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, this->mutable_value())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_FIXED32) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 1, 10, input, this->mutable_value())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void FloatArray::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated float value = 1 [packed = true];
  if (this->value_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(1, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_value_cached_byte_size_);
  }
  for (int i = 0; i < this->value_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteFloatNoTag(
      this->value(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* FloatArray::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated float value = 1 [packed = true];
  if (this->value_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      1,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
      _value_cached_byte_size_, target);
  }
  for (int i = 0; i < this->value_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteFloatNoTagToArray(this->value(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int FloatArray::ByteSize() const {
  int total_size = 0;

  // repeated float value = 1 [packed = true];
  {
    int data_size = 0;
    data_size = 4 * this->value_size();
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(data_size);
    }
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _value_cached_byte_size_ = data_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void FloatArray::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const FloatArray* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const FloatArray*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void FloatArray::MergeFrom(const FloatArray& from) {
  GOOGLE_CHECK_NE(&from, this);
  value_.MergeFrom(from.value_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void FloatArray::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FloatArray::CopyFrom(const FloatArray& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FloatArray::IsInitialized() const {

  return true;
}

void FloatArray::Swap(FloatArray* other) {
  if (other != this) {
    value_.Swap(&other->value_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata FloatArray::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = FloatArray_descriptor_;
  metadata.reflection = FloatArray_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int Mask::kValueFieldNumber;
#endif  // !_MSC_VER

Mask::Mask()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void Mask::InitAsDefaultInstance() {
}

Mask::Mask(const Mask& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void Mask::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Mask::~Mask() {
  SharedDtor();
}

void Mask::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Mask::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Mask::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Mask_descriptor_;
}

const Mask& Mask::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_internals_2eproto();
  return *default_instance_;
}

Mask* Mask::default_instance_ = NULL;

Mask* Mask::New() const {
  return new Mask;
}

void Mask::Clear() {
  value_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Mask::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated bool value = 1 [packed = true];
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, this->mutable_value())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 1, 10, input, this->mutable_value())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Mask::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated bool value = 1 [packed = true];
  if (this->value_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(1, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_value_cached_byte_size_);
  }
  for (int i = 0; i < this->value_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteBoolNoTag(
      this->value(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* Mask::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated bool value = 1 [packed = true];
  if (this->value_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      1,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
      _value_cached_byte_size_, target);
  }
  for (int i = 0; i < this->value_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteBoolNoTagToArray(this->value(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int Mask::ByteSize() const {
  int total_size = 0;

  // repeated bool value = 1 [packed = true];
  {
    int data_size = 0;
    data_size = 1 * this->value_size();
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(data_size);
    }
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _value_cached_byte_size_ = data_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Mask::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Mask* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Mask*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Mask::MergeFrom(const Mask& from) {
  GOOGLE_CHECK_NE(&from, this);
  value_.MergeFrom(from.value_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Mask::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Mask::CopyFrom(const Mask& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Mask::IsInitialized() const {

  return true;
}

void Mask::Swap(Mask* other) {
  if (other != this) {
    value_.Swap(&other->value_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Mask::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Mask_descriptor_;
  metadata.reflection = Mask_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int ProcessorInput::kBatchFieldNumber;
const int ProcessorInput::kBatchUuidFieldNumber;
const int ProcessorInput::kDataLoaderIdFieldNumber;
const int ProcessorInput::kStreamMaskFieldNumber;
const int ProcessorInput::kStreamNameFieldNumber;
const int ProcessorInput::kPreviousProcessorOutputFieldNumber;
#endif  // !_MSC_VER

ProcessorInput::ProcessorInput()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void ProcessorInput::InitAsDefaultInstance() {
  batch_ = const_cast< ::artm::Batch*>(&::artm::Batch::default_instance());
  previous_processor_output_ = const_cast< ::artm::core::ProcessorOutput*>(&::artm::core::ProcessorOutput::default_instance());
}

ProcessorInput::ProcessorInput(const ProcessorInput& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void ProcessorInput::SharedCtor() {
  _cached_size_ = 0;
  batch_ = NULL;
  batch_uuid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  data_loader_id_ = 0;
  previous_processor_output_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ProcessorInput::~ProcessorInput() {
  SharedDtor();
}

void ProcessorInput::SharedDtor() {
  if (batch_uuid_ != &::google::protobuf::internal::kEmptyString) {
    delete batch_uuid_;
  }
  if (this != default_instance_) {
    delete batch_;
    delete previous_processor_output_;
  }
}

void ProcessorInput::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ProcessorInput::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ProcessorInput_descriptor_;
}

const ProcessorInput& ProcessorInput::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_internals_2eproto();
  return *default_instance_;
}

ProcessorInput* ProcessorInput::default_instance_ = NULL;

ProcessorInput* ProcessorInput::New() const {
  return new ProcessorInput;
}

void ProcessorInput::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_batch()) {
      if (batch_ != NULL) batch_->::artm::Batch::Clear();
    }
    if (has_batch_uuid()) {
      if (batch_uuid_ != &::google::protobuf::internal::kEmptyString) {
        batch_uuid_->clear();
      }
    }
    data_loader_id_ = 0;
    if (has_previous_processor_output()) {
      if (previous_processor_output_ != NULL) previous_processor_output_->::artm::core::ProcessorOutput::Clear();
    }
  }
  stream_mask_.Clear();
  stream_name_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ProcessorInput::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .artm.Batch batch = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_batch()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_batch_uuid;
        break;
      }

      // required string batch_uuid = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_batch_uuid:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_batch_uuid()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->batch_uuid().data(), this->batch_uuid().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_data_loader_id;
        break;
      }

      // required int32 data_loader_id = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_data_loader_id:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &data_loader_id_)));
          set_has_data_loader_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_stream_mask;
        break;
      }

      // repeated .artm.core.Mask stream_mask = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_stream_mask:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_stream_mask()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_stream_mask;
        if (input->ExpectTag(42)) goto parse_stream_name;
        break;
      }

      // repeated string stream_name = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_stream_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_stream_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->stream_name(this->stream_name_size() - 1).data(),
            this->stream_name(this->stream_name_size() - 1).length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(42)) goto parse_stream_name;
        if (input->ExpectTag(50)) goto parse_previous_processor_output;
        break;
      }

      // optional .artm.core.ProcessorOutput previous_processor_output = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_previous_processor_output:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_previous_processor_output()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void ProcessorInput::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required .artm.Batch batch = 1;
  if (has_batch()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->batch(), output);
  }

  // required string batch_uuid = 2;
  if (has_batch_uuid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->batch_uuid().data(), this->batch_uuid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->batch_uuid(), output);
  }

  // required int32 data_loader_id = 3;
  if (has_data_loader_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->data_loader_id(), output);
  }

  // repeated .artm.core.Mask stream_mask = 4;
  for (int i = 0; i < this->stream_mask_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->stream_mask(i), output);
  }

  // repeated string stream_name = 5;
  for (int i = 0; i < this->stream_name_size(); i++) {
  ::google::protobuf::internal::WireFormat::VerifyUTF8String(
    this->stream_name(i).data(), this->stream_name(i).length(),
    ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      5, this->stream_name(i), output);
  }

  // optional .artm.core.ProcessorOutput previous_processor_output = 6;
  if (has_previous_processor_output()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      6, this->previous_processor_output(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* ProcessorInput::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required .artm.Batch batch = 1;
  if (has_batch()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->batch(), target);
  }

  // required string batch_uuid = 2;
  if (has_batch_uuid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->batch_uuid().data(), this->batch_uuid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->batch_uuid(), target);
  }

  // required int32 data_loader_id = 3;
  if (has_data_loader_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->data_loader_id(), target);
  }

  // repeated .artm.core.Mask stream_mask = 4;
  for (int i = 0; i < this->stream_mask_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        4, this->stream_mask(i), target);
  }

  // repeated string stream_name = 5;
  for (int i = 0; i < this->stream_name_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->stream_name(i).data(), this->stream_name(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(5, this->stream_name(i), target);
  }

  // optional .artm.core.ProcessorOutput previous_processor_output = 6;
  if (has_previous_processor_output()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        6, this->previous_processor_output(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int ProcessorInput::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .artm.Batch batch = 1;
    if (has_batch()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->batch());
    }

    // required string batch_uuid = 2;
    if (has_batch_uuid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->batch_uuid());
    }

    // required int32 data_loader_id = 3;
    if (has_data_loader_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->data_loader_id());
    }

    // optional .artm.core.ProcessorOutput previous_processor_output = 6;
    if (has_previous_processor_output()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->previous_processor_output());
    }

  }
  // repeated .artm.core.Mask stream_mask = 4;
  total_size += 1 * this->stream_mask_size();
  for (int i = 0; i < this->stream_mask_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->stream_mask(i));
  }

  // repeated string stream_name = 5;
  total_size += 1 * this->stream_name_size();
  for (int i = 0; i < this->stream_name_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->stream_name(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ProcessorInput::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ProcessorInput* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ProcessorInput*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ProcessorInput::MergeFrom(const ProcessorInput& from) {
  GOOGLE_CHECK_NE(&from, this);
  stream_mask_.MergeFrom(from.stream_mask_);
  stream_name_.MergeFrom(from.stream_name_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_batch()) {
      mutable_batch()->::artm::Batch::MergeFrom(from.batch());
    }
    if (from.has_batch_uuid()) {
      set_batch_uuid(from.batch_uuid());
    }
    if (from.has_data_loader_id()) {
      set_data_loader_id(from.data_loader_id());
    }
    if (from.has_previous_processor_output()) {
      mutable_previous_processor_output()->::artm::core::ProcessorOutput::MergeFrom(from.previous_processor_output());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ProcessorInput::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ProcessorInput::CopyFrom(const ProcessorInput& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ProcessorInput::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  if (has_previous_processor_output()) {
    if (!this->previous_processor_output().IsInitialized()) return false;
  }
  return true;
}

void ProcessorInput::Swap(ProcessorInput* other) {
  if (other != this) {
    std::swap(batch_, other->batch_);
    std::swap(batch_uuid_, other->batch_uuid_);
    std::swap(data_loader_id_, other->data_loader_id_);
    stream_mask_.Swap(&other->stream_mask_);
    stream_name_.Swap(&other->stream_name_);
    std::swap(previous_processor_output_, other->previous_processor_output_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ProcessorInput::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ProcessorInput_descriptor_;
  metadata.reflection = ProcessorInput_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int ProcessorOutput::kBatchUuidFieldNumber;
const int ProcessorOutput::kDataLoaderIdFieldNumber;
const int ProcessorOutput::kModelIncrementFieldNumber;
#endif  // !_MSC_VER

ProcessorOutput::ProcessorOutput()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void ProcessorOutput::InitAsDefaultInstance() {
}

ProcessorOutput::ProcessorOutput(const ProcessorOutput& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void ProcessorOutput::SharedCtor() {
  _cached_size_ = 0;
  batch_uuid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  data_loader_id_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ProcessorOutput::~ProcessorOutput() {
  SharedDtor();
}

void ProcessorOutput::SharedDtor() {
  if (batch_uuid_ != &::google::protobuf::internal::kEmptyString) {
    delete batch_uuid_;
  }
  if (this != default_instance_) {
  }
}

void ProcessorOutput::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ProcessorOutput::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ProcessorOutput_descriptor_;
}

const ProcessorOutput& ProcessorOutput::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_internals_2eproto();
  return *default_instance_;
}

ProcessorOutput* ProcessorOutput::default_instance_ = NULL;

ProcessorOutput* ProcessorOutput::New() const {
  return new ProcessorOutput;
}

void ProcessorOutput::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_batch_uuid()) {
      if (batch_uuid_ != &::google::protobuf::internal::kEmptyString) {
        batch_uuid_->clear();
      }
    }
    data_loader_id_ = 0;
  }
  model_increment_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ProcessorOutput::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string batch_uuid = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_batch_uuid()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->batch_uuid().data(), this->batch_uuid().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_data_loader_id;
        break;
      }

      // required int32 data_loader_id = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_data_loader_id:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &data_loader_id_)));
          set_has_data_loader_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_model_increment;
        break;
      }

      // repeated .artm.core.ModelIncrement model_increment = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_model_increment:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_model_increment()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_model_increment;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void ProcessorOutput::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string batch_uuid = 1;
  if (has_batch_uuid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->batch_uuid().data(), this->batch_uuid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->batch_uuid(), output);
  }

  // required int32 data_loader_id = 2;
  if (has_data_loader_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->data_loader_id(), output);
  }

  // repeated .artm.core.ModelIncrement model_increment = 3;
  for (int i = 0; i < this->model_increment_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->model_increment(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* ProcessorOutput::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string batch_uuid = 1;
  if (has_batch_uuid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->batch_uuid().data(), this->batch_uuid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->batch_uuid(), target);
  }

  // required int32 data_loader_id = 2;
  if (has_data_loader_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->data_loader_id(), target);
  }

  // repeated .artm.core.ModelIncrement model_increment = 3;
  for (int i = 0; i < this->model_increment_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->model_increment(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int ProcessorOutput::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string batch_uuid = 1;
    if (has_batch_uuid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->batch_uuid());
    }

    // required int32 data_loader_id = 2;
    if (has_data_loader_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->data_loader_id());
    }

  }
  // repeated .artm.core.ModelIncrement model_increment = 3;
  total_size += 1 * this->model_increment_size();
  for (int i = 0; i < this->model_increment_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->model_increment(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ProcessorOutput::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ProcessorOutput* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ProcessorOutput*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ProcessorOutput::MergeFrom(const ProcessorOutput& from) {
  GOOGLE_CHECK_NE(&from, this);
  model_increment_.MergeFrom(from.model_increment_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_batch_uuid()) {
      set_batch_uuid(from.batch_uuid());
    }
    if (from.has_data_loader_id()) {
      set_data_loader_id(from.data_loader_id());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ProcessorOutput::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ProcessorOutput::CopyFrom(const ProcessorOutput& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ProcessorOutput::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  for (int i = 0; i < model_increment_size(); i++) {
    if (!this->model_increment(i).IsInitialized()) return false;
  }
  return true;
}

void ProcessorOutput::Swap(ProcessorOutput* other) {
  if (other != this) {
    std::swap(batch_uuid_, other->batch_uuid_);
    std::swap(data_loader_id_, other->data_loader_id_);
    model_increment_.Swap(&other->model_increment_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ProcessorOutput::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ProcessorOutput_descriptor_;
  metadata.reflection = ProcessorOutput_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int ModelIncrement::kModelIdFieldNumber;
const int ModelIncrement::kTopicsCountFieldNumber;
const int ModelIncrement::kItemsProcessedFieldNumber;
const int ModelIncrement::kDiscoveredTokenFieldNumber;
const int ModelIncrement::kTokenFieldNumber;
const int ModelIncrement::kTokenIncrementFieldNumber;
const int ModelIncrement::kScoreFieldNumber;
const int ModelIncrement::kScoreNormFieldNumber;
const int ModelIncrement::kItemIdFieldNumber;
const int ModelIncrement::kThetaFieldNumber;
#endif  // !_MSC_VER

ModelIncrement::ModelIncrement()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void ModelIncrement::InitAsDefaultInstance() {
}

ModelIncrement::ModelIncrement(const ModelIncrement& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void ModelIncrement::SharedCtor() {
  _cached_size_ = 0;
  model_id_ = 0;
  topics_count_ = 0;
  items_processed_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ModelIncrement::~ModelIncrement() {
  SharedDtor();
}

void ModelIncrement::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ModelIncrement::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ModelIncrement::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ModelIncrement_descriptor_;
}

const ModelIncrement& ModelIncrement::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_internals_2eproto();
  return *default_instance_;
}

ModelIncrement* ModelIncrement::default_instance_ = NULL;

ModelIncrement* ModelIncrement::New() const {
  return new ModelIncrement;
}

void ModelIncrement::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    model_id_ = 0;
    topics_count_ = 0;
    items_processed_ = 0;
  }
  discovered_token_.Clear();
  token_.Clear();
  token_increment_.Clear();
  score_.Clear();
  score_norm_.Clear();
  item_id_.Clear();
  theta_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ModelIncrement::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 model_id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &model_id_)));
          set_has_model_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_topics_count;
        break;
      }

      // required int32 topics_count = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_topics_count:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &topics_count_)));
          set_has_topics_count();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_items_processed;
        break;
      }

      // optional int32 items_processed = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_items_processed:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &items_processed_)));
          set_has_items_processed();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_discovered_token;
        break;
      }

      // repeated string discovered_token = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_discovered_token:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_discovered_token()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->discovered_token(this->discovered_token_size() - 1).data(),
            this->discovered_token(this->discovered_token_size() - 1).length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_discovered_token;
        if (input->ExpectTag(42)) goto parse_token;
        break;
      }

      // repeated string token = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_token:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_token()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->token(this->token_size() - 1).data(),
            this->token(this->token_size() - 1).length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(42)) goto parse_token;
        if (input->ExpectTag(50)) goto parse_token_increment;
        break;
      }

      // repeated .artm.core.FloatArray token_increment = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_token_increment:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_token_increment()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(50)) goto parse_token_increment;
        if (input->ExpectTag(57)) goto parse_score;
        break;
      }

      // repeated double score = 7;
      case 7: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
         parse_score:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 1, 57, input, this->mutable_score())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, this->mutable_score())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(57)) goto parse_score;
        if (input->ExpectTag(65)) goto parse_score_norm;
        break;
      }

      // repeated double score_norm = 8;
      case 8: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
         parse_score_norm:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 1, 65, input, this->mutable_score_norm())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, this->mutable_score_norm())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(65)) goto parse_score_norm;
        if (input->ExpectTag(72)) goto parse_item_id;
        break;
      }

      // repeated int32 item_id = 9;
      case 9: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_item_id:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 72, input, this->mutable_item_id())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_item_id())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(72)) goto parse_item_id;
        if (input->ExpectTag(82)) goto parse_theta;
        break;
      }

      // repeated .artm.core.FloatArray theta = 10;
      case 10: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_theta:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_theta()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(82)) goto parse_theta;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void ModelIncrement::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 model_id = 1;
  if (has_model_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->model_id(), output);
  }

  // required int32 topics_count = 2;
  if (has_topics_count()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->topics_count(), output);
  }

  // optional int32 items_processed = 3;
  if (has_items_processed()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->items_processed(), output);
  }

  // repeated string discovered_token = 4;
  for (int i = 0; i < this->discovered_token_size(); i++) {
  ::google::protobuf::internal::WireFormat::VerifyUTF8String(
    this->discovered_token(i).data(), this->discovered_token(i).length(),
    ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      4, this->discovered_token(i), output);
  }

  // repeated string token = 5;
  for (int i = 0; i < this->token_size(); i++) {
  ::google::protobuf::internal::WireFormat::VerifyUTF8String(
    this->token(i).data(), this->token(i).length(),
    ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      5, this->token(i), output);
  }

  // repeated .artm.core.FloatArray token_increment = 6;
  for (int i = 0; i < this->token_increment_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      6, this->token_increment(i), output);
  }

  // repeated double score = 7;
  for (int i = 0; i < this->score_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(
      7, this->score(i), output);
  }

  // repeated double score_norm = 8;
  for (int i = 0; i < this->score_norm_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(
      8, this->score_norm(i), output);
  }

  // repeated int32 item_id = 9;
  for (int i = 0; i < this->item_id_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      9, this->item_id(i), output);
  }

  // repeated .artm.core.FloatArray theta = 10;
  for (int i = 0; i < this->theta_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      10, this->theta(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* ModelIncrement::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 model_id = 1;
  if (has_model_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->model_id(), target);
  }

  // required int32 topics_count = 2;
  if (has_topics_count()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->topics_count(), target);
  }

  // optional int32 items_processed = 3;
  if (has_items_processed()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->items_processed(), target);
  }

  // repeated string discovered_token = 4;
  for (int i = 0; i < this->discovered_token_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->discovered_token(i).data(), this->discovered_token(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(4, this->discovered_token(i), target);
  }

  // repeated string token = 5;
  for (int i = 0; i < this->token_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->token(i).data(), this->token(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(5, this->token(i), target);
  }

  // repeated .artm.core.FloatArray token_increment = 6;
  for (int i = 0; i < this->token_increment_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        6, this->token_increment(i), target);
  }

  // repeated double score = 7;
  for (int i = 0; i < this->score_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteDoubleToArray(7, this->score(i), target);
  }

  // repeated double score_norm = 8;
  for (int i = 0; i < this->score_norm_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteDoubleToArray(8, this->score_norm(i), target);
  }

  // repeated int32 item_id = 9;
  for (int i = 0; i < this->item_id_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(9, this->item_id(i), target);
  }

  // repeated .artm.core.FloatArray theta = 10;
  for (int i = 0; i < this->theta_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        10, this->theta(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int ModelIncrement::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 model_id = 1;
    if (has_model_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->model_id());
    }

    // required int32 topics_count = 2;
    if (has_topics_count()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->topics_count());
    }

    // optional int32 items_processed = 3;
    if (has_items_processed()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->items_processed());
    }

  }
  // repeated string discovered_token = 4;
  total_size += 1 * this->discovered_token_size();
  for (int i = 0; i < this->discovered_token_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->discovered_token(i));
  }

  // repeated string token = 5;
  total_size += 1 * this->token_size();
  for (int i = 0; i < this->token_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->token(i));
  }

  // repeated .artm.core.FloatArray token_increment = 6;
  total_size += 1 * this->token_increment_size();
  for (int i = 0; i < this->token_increment_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->token_increment(i));
  }

  // repeated double score = 7;
  {
    int data_size = 0;
    data_size = 8 * this->score_size();
    total_size += 1 * this->score_size() + data_size;
  }

  // repeated double score_norm = 8;
  {
    int data_size = 0;
    data_size = 8 * this->score_norm_size();
    total_size += 1 * this->score_norm_size() + data_size;
  }

  // repeated int32 item_id = 9;
  {
    int data_size = 0;
    for (int i = 0; i < this->item_id_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->item_id(i));
    }
    total_size += 1 * this->item_id_size() + data_size;
  }

  // repeated .artm.core.FloatArray theta = 10;
  total_size += 1 * this->theta_size();
  for (int i = 0; i < this->theta_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->theta(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ModelIncrement::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ModelIncrement* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ModelIncrement*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ModelIncrement::MergeFrom(const ModelIncrement& from) {
  GOOGLE_CHECK_NE(&from, this);
  discovered_token_.MergeFrom(from.discovered_token_);
  token_.MergeFrom(from.token_);
  token_increment_.MergeFrom(from.token_increment_);
  score_.MergeFrom(from.score_);
  score_norm_.MergeFrom(from.score_norm_);
  item_id_.MergeFrom(from.item_id_);
  theta_.MergeFrom(from.theta_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_model_id()) {
      set_model_id(from.model_id());
    }
    if (from.has_topics_count()) {
      set_topics_count(from.topics_count());
    }
    if (from.has_items_processed()) {
      set_items_processed(from.items_processed());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ModelIncrement::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ModelIncrement::CopyFrom(const ModelIncrement& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ModelIncrement::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void ModelIncrement::Swap(ModelIncrement* other) {
  if (other != this) {
    std::swap(model_id_, other->model_id_);
    std::swap(topics_count_, other->topics_count_);
    std::swap(items_processed_, other->items_processed_);
    discovered_token_.Swap(&other->discovered_token_);
    token_.Swap(&other->token_);
    token_increment_.Swap(&other->token_increment_);
    score_.Swap(&other->score_);
    score_norm_.Swap(&other->score_norm_);
    item_id_.Swap(&other->item_id_);
    theta_.Swap(&other->theta_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ModelIncrement::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ModelIncrement_descriptor_;
  metadata.reflection = ModelIncrement_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace core
}  // namespace artm

// @@protoc_insertion_point(global_scope)
