cp ../../src/Win32/Release/artm.dll BigARTM/
cp ../../src/Win32/Release/node_controller.dll BigARTM/
cp ../../src/Win32/Release/libglog.dll BigARTM/
cp ../../src/Win32/Release/libzmq-v110-mt-4_0_4.dll BigARTM/
cp ../../src/artm/messages.proto BigARTM/
cp ../../src/python_interface/python_interface.py BigARTM/
cp ../../src/python_interface/messages_pb2.py BigARTM/
cp ../../datasets/vocab.kos.txt .
cp ../../datasets/docword.kos.txt .
