# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='api.proto',
  package='topicmd',
  serialized_pb='\n\tapi.proto\x12\x07topicmd\"\xb2\x02\n\x0bItemsVector\x12\x38\n\x10\x63ontract_version\x18\x01 \x01(\x0e\x32\x18.topicmd.ContractVersion:\x04V_01\x12\x0e\n\x06tokens\x18\x02 \x03(\t\x12(\n\x05items\x18\x03 \x03(\x0b\x32\x19.topicmd.ItemsVector.Item\x1az\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\x05\x12=\n\toperation\x18\x02 \x01(\x0e\x32\".topicmd.ItemsVector.OperationType:\x06INSERT\x12\x11\n\ttoken_ids\x18\x03 \x03(\x05\x12\x14\n\x0ctoken_counts\x18\x04 \x03(\x05\"3\n\rOperationType\x12\n\n\x06INSERT\x10\x00\x12\n\n\x06UPDATE\x10\x01\x12\n\n\x06\x44\x45LETE\x10\x02\"\xe8\x01\n\rConfiguration\x12\x38\n\x10\x63ontract_version\x18\x01 \x01(\x0e\x32\x18.topicmd.ContractVersion:\x04V_01\x12\x16\n\x0eindex_location\x18\x02 \x01(\t\x12\'\n\x18process_items_on_publish\x18\x03 \x01(\x08:\x05\x66\x61lse\x12\x1e\n\x13index_readers_count\x18\x04 \x01(\x05:\x01\x31\x12\x1b\n\x10processors_count\x18\x05 \x01(\x05:\x01\x31\"\x1f\n\rProcessorType\x12\x0e\n\nBATCH_PLSA\x10\x00\"\x9c\x01\n\x13LoggerConfiguration\x12\x14\n\x0clog_location\x18\x01 \x01(\t\x12\x37\n\x05level\x18\x02 \x01(\x0e\x32\".topicmd.LoggerConfiguration.Level:\x04INFO\"6\n\x05Level\x12\t\n\x05\x45RROR\x10\x01\x12\x0b\n\x07WARNING\x10\x02\x12\x08\n\x04INFO\x10\x03\x12\x0b\n\x07VERBOSE\x10\x04*\x1b\n\x0f\x43ontractVersion\x12\x08\n\x04V_01\x10\x00')

_CONTRACTVERSION = _descriptor.EnumDescriptor(
  name='ContractVersion',
  full_name='topicmd.ContractVersion',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='V_01', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=725,
  serialized_end=752,
)

ContractVersion = enum_type_wrapper.EnumTypeWrapper(_CONTRACTVERSION)
V_01 = 0


_ITEMSVECTOR_OPERATIONTYPE = _descriptor.EnumDescriptor(
  name='OperationType',
  full_name='topicmd.ItemsVector.OperationType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INSERT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UPDATE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DELETE', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=278,
  serialized_end=329,
)

_CONFIGURATION_PROCESSORTYPE = _descriptor.EnumDescriptor(
  name='ProcessorType',
  full_name='topicmd.Configuration.ProcessorType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BATCH_PLSA', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=533,
  serialized_end=564,
)

_LOGGERCONFIGURATION_LEVEL = _descriptor.EnumDescriptor(
  name='Level',
  full_name='topicmd.LoggerConfiguration.Level',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WARNING', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INFO', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VERBOSE', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=669,
  serialized_end=723,
)


_ITEMSVECTOR_ITEM = _descriptor.Descriptor(
  name='Item',
  full_name='topicmd.ItemsVector.Item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='topicmd.ItemsVector.Item.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='operation', full_name='topicmd.ItemsVector.Item.operation', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='token_ids', full_name='topicmd.ItemsVector.Item.token_ids', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='token_counts', full_name='topicmd.ItemsVector.Item.token_counts', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=154,
  serialized_end=276,
)

_ITEMSVECTOR = _descriptor.Descriptor(
  name='ItemsVector',
  full_name='topicmd.ItemsVector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='contract_version', full_name='topicmd.ItemsVector.contract_version', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tokens', full_name='topicmd.ItemsVector.tokens', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='items', full_name='topicmd.ItemsVector.items', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_ITEMSVECTOR_ITEM, ],
  enum_types=[
    _ITEMSVECTOR_OPERATIONTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=23,
  serialized_end=329,
)


_CONFIGURATION = _descriptor.Descriptor(
  name='Configuration',
  full_name='topicmd.Configuration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='contract_version', full_name='topicmd.Configuration.contract_version', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='index_location', full_name='topicmd.Configuration.index_location', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='process_items_on_publish', full_name='topicmd.Configuration.process_items_on_publish', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='index_readers_count', full_name='topicmd.Configuration.index_readers_count', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='processors_count', full_name='topicmd.Configuration.processors_count', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CONFIGURATION_PROCESSORTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=332,
  serialized_end=564,
)


_LOGGERCONFIGURATION = _descriptor.Descriptor(
  name='LoggerConfiguration',
  full_name='topicmd.LoggerConfiguration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='log_location', full_name='topicmd.LoggerConfiguration.log_location', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='level', full_name='topicmd.LoggerConfiguration.level', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=3,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _LOGGERCONFIGURATION_LEVEL,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=567,
  serialized_end=723,
)

_ITEMSVECTOR_ITEM.fields_by_name['operation'].enum_type = _ITEMSVECTOR_OPERATIONTYPE
_ITEMSVECTOR_ITEM.containing_type = _ITEMSVECTOR;
_ITEMSVECTOR.fields_by_name['contract_version'].enum_type = _CONTRACTVERSION
_ITEMSVECTOR.fields_by_name['items'].message_type = _ITEMSVECTOR_ITEM
_ITEMSVECTOR_OPERATIONTYPE.containing_type = _ITEMSVECTOR;
_CONFIGURATION.fields_by_name['contract_version'].enum_type = _CONTRACTVERSION
_CONFIGURATION_PROCESSORTYPE.containing_type = _CONFIGURATION;
_LOGGERCONFIGURATION.fields_by_name['level'].enum_type = _LOGGERCONFIGURATION_LEVEL
_LOGGERCONFIGURATION_LEVEL.containing_type = _LOGGERCONFIGURATION;
DESCRIPTOR.message_types_by_name['ItemsVector'] = _ITEMSVECTOR
DESCRIPTOR.message_types_by_name['Configuration'] = _CONFIGURATION
DESCRIPTOR.message_types_by_name['LoggerConfiguration'] = _LOGGERCONFIGURATION

class ItemsVector(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class Item(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _ITEMSVECTOR_ITEM

    # @@protoc_insertion_point(class_scope:topicmd.ItemsVector.Item)
  DESCRIPTOR = _ITEMSVECTOR

  # @@protoc_insertion_point(class_scope:topicmd.ItemsVector)

class Configuration(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONFIGURATION

  # @@protoc_insertion_point(class_scope:topicmd.Configuration)

class LoggerConfiguration(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOGGERCONFIGURATION

  # @@protoc_insertion_point(class_scope:topicmd.LoggerConfiguration)


# @@protoc_insertion_point(module_scope)
