call cpplint.bat ../src/artm/boost_thread_test.cc
call cpplint.bat ../src/artm/cpp_interface.cc
call cpplint.bat ../src/artm/cpp_interface_unittest.cc
call cpplint.bat ../src/artm/c_interface.cc
call cpplint.bat ../src/artm/data_loader.cc
call cpplint.bat ../src/artm/dirichlet_regularizer_phi.cc
call cpplint.bat ../src/artm/dirichlet_regularizer_theta.cc
call cpplint.bat ../src/artm/generation.cc
call cpplint.bat ../src/artm/helpers.cc
call cpplint.bat ../src/artm/instance.cc
call cpplint.bat ../src/artm/instance_manager_test.cc
call cpplint.bat ../src/artm/instance_schema.cc
call cpplint.bat ../src/artm/instance_test.cc
call cpplint.bat ../src/artm/master_component.cc
call cpplint.bat ../src/artm/memcached_server.cc
call cpplint.bat ../src/artm/memcached_service_impl.cc
call cpplint.bat ../src/artm/memcached_service_test.cc
call cpplint.bat ../src/artm/merger.cc
call cpplint.bat ../src/artm/processor.cc
call cpplint.bat ../src/artm/topic_model.cc
call cpplint.bat ../src/artm/topic_model_test.cc

call cpplint.bat ../src/artm/call_on_destruction.h
call cpplint.bat ../src/artm/common.h
call cpplint.bat ../src/artm/cpp_interface.h
call cpplint.bat ../src/artm/c_interface.h
call cpplint.bat ../src/artm/data_loader.h
call cpplint.bat ../src/artm/dirichlet_regularizer_phi.h
call cpplint.bat ../src/artm/dirichlet_regularizer_theta.h
call cpplint.bat ../src/artm/exceptions.h
call cpplint.bat ../src/artm/generation.h
call cpplint.bat ../src/artm/helpers.h
call cpplint.bat ../src/artm/instance.h
call cpplint.bat ../src/artm/instance_schema.h
call cpplint.bat ../src/artm/master_component.h
call cpplint.bat ../src/artm/memcached_server.h
call cpplint.bat ../src/artm/memcached_service_impl.h
call cpplint.bat ../src/artm/merger.h
call cpplint.bat ../src/artm/processor.h
call cpplint.bat ../src/artm/protobuf_helpers.h
call cpplint.bat ../src/artm/regularizer_interface.h
call cpplint.bat ../src/artm/template_manager.h
call cpplint.bat ../src/artm/thread_safe_holder.h
call cpplint.bat ../src/artm/topic_model.h